//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulpep.PayU.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tulpep_PayUResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tulpep_PayUResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tulpep.PayU.Library.Resources.Tulpep_PayUResources", typeof(Tulpep_PayUResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 551311.
        /// </summary>
        internal static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0kzhe907m8jE0nInkJwgZpAA2W.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jdX6oONZO8485i1.
        /// </summary>
        internal static string APILogin {
            get {
                return ResourceManager.GetString("APILogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.payulatam.com/payments-api/4.0/service.cgi.
        /// </summary>
        internal static string DefaultProductionPaymentsConnectionUrl {
            get {
                return ResourceManager.GetString("DefaultProductionPaymentsConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.payulatam.com/reports-api/4.0/service.cgi.
        /// </summary>
        internal static string DefaultProductionQueriesConnectionUrl {
            get {
                return ResourceManager.GetString("DefaultProductionQueriesConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://184.72.122.69/payments-api/4.0/service.cgi.
        /// </summary>
        internal static string DefaultTestPaymentsConnectionUrl {
            get {
                return ResourceManager.GetString("DefaultTestPaymentsConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://184.72.122.69/reports-api/4.0/service.cgi.
        /// </summary>
        internal static string DefaultTestQueriesConnectionUrl {
            get {
                return ResourceManager.GetString("DefaultTestQueriesConnectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500538.
        /// </summary>
        internal static string TestAccountId {
            get {
                return ResourceManager.GetString("TestAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6u39nqhq8ftd0hlvnjfs66eh8c.
        /// </summary>
        internal static string TestAPIKey {
            get {
                return ResourceManager.GetString("TestAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11959c415b33d0c.
        /// </summary>
        internal static string TestAPILogin {
            get {
                return ResourceManager.GetString("TestAPILogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500238.
        /// </summary>
        internal static string TestMerchantId {
            get {
                return ResourceManager.GetString("TestMerchantId", resourceCulture);
            }
        }
    }
}
